# Example configuration file for the server

# The port that the http server will run on
httpPort: 3000
# The port that the websocket server will run on
wsPort: 8080
# How often to check a user's ban status
banCheckInterval: 60000
# The capabilities that will be granted to users by default
defaultCapabilities:
- tell
- markdown
- format
- receive
- commands
- list_players
- join_leave
- death